spring:
  application:
    name: wish-service
  datasource:
    # MySQL
    url: jdbc:mysql://localhost:3306/spring_boot_test?useSSL=false
    username: root
    password: ashy1992
    driver-class-name: com.mysql.jdbc.Driver

info:
  app:
    name: wish-service

server:
  context-path: /wish-service
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance-id:${server.port:8080}}
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 30
    health-check-url-path: ${server.context-path}/health
    status-page-url-path: ${server.context-path}/info
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    hy:
      spring:
        boot:
          mybatis: debug